server:
  port: 8080

rabbitmq:
  retry:
    delay-in-ms: 1000
    count: 3

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:29000/alarm"
    username: root
    password: admin

  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: '28300'
    listener:
      simple:
        default-requeue-rejected: 'false'

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3_single
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:43000/api/v2/spans"
