spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: playlistdb
      username: root
      password: 1234
      authentication-database: admin

    redis:
      port: 6379
      host: redis

server:
  port: 16002
