version: "3.9"

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile.elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "20001:9200"
    networks:
      - backend
    volumes:
      - ./es_data_volume:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://localhost:20001
      - xpack.security.enabled=false

    networks:
      - backend
    depends_on:
      - elasticsearch

  search-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20000:8000"
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - elasticsearch
  
networks:
  backend: