version: "3.9"

services:
  search-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "20000:8000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - elasticsearch
    networks:
      - lalala-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
    ports:
      - "21000:9200"

networks:
  lalala-network:
    driver: bridge
    external: true
