version: "3.9"

services:
  chart-mongo:
    image: mongo:7.0.5
    container_name: chart-mongo
    restart: always
    ports:
      - 26100:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: chipmunk
      MONGO_INITDB_ROOT_PASSWORD: JMTpdsu8YkLEXBW4RA
      MONGO_INITDB_DATABASE: chart
    volumes:
      - chart-mongodbdata:/data/db:cached
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  chart-mongo-express:
    image: mongo-express:1.0.2
    restart: always
    ports:
      - 26900:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: chipmunk
      ME_CONFIG_MONGODB_ADMINPASSWORD: JMTpdsu8YkLEXBW4RA
      ME_CONFIG_MONGODB_SERVER: chart-mongo
      ME_CONFIG_BASICAUTH_USERNAME: chipmunk-admin
      ME_CONFIG_BASICAUTH_PASSWORD: g2+u*8XG%^xKT=-SzDMfbZ

  chart-batch-mysql:
    image: mysql:8.2.0
    restart: always
    ports:
      - 27100:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: chart
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
      - ./infra/:/docker-entrypoint-initdb.d

volumes:
  chart-mongodbdata:
    driver: local
