version: '3'

services:
  redis:
    container_name: test-redis
    image: redis:7.0-alpine
    hostname: test-redis
    ports:
      - "16379:6379"
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"