version: '3.8'

services:
  mongodb:
    image: mongo:7.0.5
    ports:
      - "18001:18001"
    env_file: .env
    container_name: chattingdb
    hostname: mongodb
    volumes:
      - ./database/mongoDB/data:/data/db
      - ./database/mongoDB/initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - chatting-network

  chatting:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18000:18000"
    depends_on:
      - mongodb
    networks:
      - chatting-network

networks:
  chatting-network: