version: "3.9"
services:
  gateway-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 34000:34000
    networks:
      - lalala-network

networks:
  lalala-network:
    driver: bridge
    external: true
