version: '3'

services:
  neo4j:
    container_name: test-neo4j
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins: