version: "3.9"

services:
  music-uploader-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - STORAGE_URL=http://fileserver-app
    ports:
      - "25000:3000"
    volumes:
      - ./:/app/
    networks:
      - lalala-network

networks:
  lalala-network:
    driver: bridge
    external: true
