version: '3.9'

services:
  app:
    container_name: streaming-server
    ports:
      - "22000:22000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - client.endpoint.music=http://host.docker.internal:24000
      - client.endpoint.storage=http://host.docker.internal:30000
    restart: always
    networks:
      - streaming-network

networks:
  streaming-network:
