version: '3.9'

services:
  streaming-app:
    ports:
      - "22000:22000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - client.endpoint.music=http://music-app:24000
      - client.endpoint.storage=http://music-uploader-app:30000
    restart: always
    networks:
      - lalala-network

networks:
  lalala-network:
    driver: bridge
    external: true
