version: "3.9"
services:
  feed-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      SPRING_NEO4J_URI: bolt://feed-neo4j:14200
      SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: password
    ports:
      - 14000:14000
    networks:
      - lalala-network

  feed-neo4j:
    image: neo4j
    ports:
      - "14100:7474"
      - "14200:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:

networks:
  lalala-network:
    driver: bridge
    external: true
