version: '3.9'
services:
  music-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 24000:24000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://music-mysql:3306/music?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - music-mysql
    networks:
      - lalala-network

  music-mysql:
    image: mysql:8.2.0
    container_name: music-db
    restart: always
    ports:
      - 24100:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: music
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
      - ./infra/:/docker-entrypoint-initdb.d
    networks:
      - lalala-network

  music-adminer:
    image: adminer
    container_name: music-adminer
    restart: always
    ports:
      - 24900:8080
    networks:
      - lalala-network

networks:
  lalala-network:
    driver: bridge
    external: true
