version: '3.9'
services:
  music-mysql:
    image: mysql:8.2.0
    container_name: music-db
    restart: always
    ports:
      - 24100:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: music
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
      - ./infra/:/docker-entrypoint-initdb.d
    networks:
      - lalala-network

  music-adminer:
    image: adminer
    container_name: music-adminer
    restart: always
    ports:
      - 24900:8080
    networks:
      - lalala-network

networks:
  lalala-network:
    driver: bridge
    external: true
