server:
  port: 12000

spring:
  application:
    name: user-server

  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:12100/user?useSSL=false&allowPublicKeyRetrieval=true
     username: root
     password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 12200
  mail:
    host: smtp.gmail.com
    port: 465
    username: smilegate.wannabe@gmail.com
    password: hxir xfcg rzec atni
    auth: true
    starttls:
      enable: true
    protocol: smtps

  kafka:
    bootstrap-servers: localhost:40000,localhost:40001,localhost:40002

jwt:
  cookie-max-age: 86400 #1day
  secret-key: c21pbGVnYXRlLWNvbXBhbnktaXMtdG9vLWZhci1zby1pLXdhbnQtdG8td29yay1mcm9tLWhvbWUtZXZlcnktb3RoZXItZGF5Cg==

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:34100/eureka

passport:
  algorithm: SHA-256
  key: SECRET_KEY

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3_single
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:43000/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
