server:
  port: 16000

spring:
  application:
    name: playlist-server

  data:
    mongodb:
      host: localhost
      port: 16100
      database: playlist
      username: admin
      password: QOdmQodmsapomd41dM
      authentication-database: admin

    redis:
      host: localhost
      port: 16200

  kafka:
    bootstrap-servers: localhost:40000,localhost:40001,localhost:40002

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:34100/eureka

passport:
  algorithm: HmacSHA256
  key: SECRET_KEY

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: [b3, w3c]
      produce: [b3, w3c]
  zipkin:
    tracing:
      endpoint: "http://localhost:43000/api/v2/spans"

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
