version: "3.9"

services:
  fileserver-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30000:30000"
    restart: unless-stopped
    environment:
      - PORT=30000
      - ENV=develop
    networks:
      - lalala-network
    volumes:
      - ./resources:/resources

networks:
  lalala-network:
    driver: bridge
    external: true
